FORMAT: 1A
HOST: https://densityexample.local

# Campus Density

Campus Density API Doc

## Authentication v1 [/authv1]

### Get an API Token [PUT]

+ Request (application/json) 
    
    + Headers

            Authorization: Bearer [API_KEY]
            x-api-key: (PlatformIdentifier)


    + Attributes (AuthResponse)
    

+ Response 201

    Successful response.
 
    + Headers
            
            content-type: application/json
       
    + Body

            { 
                token: "[token]"
            }
    

+ Response 500

    Something went wrong inside the server.

    + Headers
            
            content-type: text/plain

    + Body

            Internal Error.

+ Response 403

    No API key given.
    
    + Headers
            
            content-type: text/plain
    
    
    + Body

            Unauthorized

+ Response 401

    Invalid API key.
    
    + Headers
            
            content-type: text/plain
    
    
    + Body

            Unable to authenticate api key.

## Facility List [/facilityList]

### Get facility list [GET]

+ Request (application/json) 
    
    + Headers

            Authorization: Bearer [API_KEY]
            x-api-key: (API Token)

+ Response 200

    Successful response.
 
    + Headers
            
            content-type: application/json
       
    + Body

            [
                {  
                  id: "facilityId",
                  displayName: "display name"
                }
            ]

+ Response 500

    Something went wrong inside the server.

    + Headers
            
            content-type: text/plain

    + Body

            Internal Error.

+ Response 403

    Unauthorized access.
    
    + Headers
            
            content-type: text/plain
    
    
    + Body

            Unauthorized

## Facility Information [/facilityInfo{?id}]

+ Parameters
    + id (string, optional) - If provided the endpoint will only return metadata for the provided id.
    


### Get facility metadata [GET]

+ Request (application/json) 
    
    + Headers

            Authorization: Bearer [API_KEY]
            x-api-key: (API Token)

+ Response 200

    Successful response.
 
    + Headers
            
            content-type: application/json
    
    + Attributes
        + Array of Metadata (array)
            + - (object)
                + id (string)
                + campusLocation (enum[string])
                    + "north" - North Campus Location
                    + "central" - Central Campus Location
                    + "west" - West Campus Location
                + nextOpen (number) - If no opening time is found it is -1, otherwise a timestamp since epoch.
                + closingAt (number) - If the restaurant is open it is -1, otherwise a timestamp since epoch.
                + description (string)
                + dailyHours (array)
    + Body

            [
                { 
                    id: "facilityId",
                    campusLocation: "north",
                    nextOpen: -1,
                    description: "description of facility",
                    closingAt: -1,
                    dailyHours: [
                        {
                            startTimestamp: 0,
                            endTimestamp: 0
                        }
                    ]
                }
            ]
    

+ Response 500

    Something went wrong inside the server.

    + Headers
            
            content-type: text/plain

    + Body

            Internal Error.

+ Response 403

    Unauthorized access.
    
    + Headers
            
            content-type: text/plain
    
    + Body

            Unauthorized

## Density Information [/howDense]

### Get list of densities [GET]

+ Request (application/json) 
    
    + Headers

            Authorization: Bearer [API_KEY]
            x-api-key: (API Token)
    

+ Response 200

    Successful response.
 
    + Headers
            
            content-type: application/json
    
    + Attributes
        + - (array)
            + - (object)
                + id: "facilityId" (string)
                + density: 0 (enum[number])
                    + 0 - Low
                    + 1 - Mid
                    + 2 - High
                    + 3 - Very High
    + Body
            
            [
                {
                    "id": "facilityId"
                    "density": 0
                }
            ]
    

+ Response 500

    Something went wrong inside the server.

    + Headers
            
            content-type: text/plain

    + Body

            Internal Error.

+ Response 403

    Unauthorized access.
    
    + Headers
            
            content-type: text/plain
    
    
    + Body

            Unauthorized

# Data Structures

## AuthResponse (object)
+ platform (enum[string], required) - Platform request originates from
    + Members
        + android
        + ios
+ receipt (string) - iOS App Receipt in Base64 \(utilize when platform=ios\)
+ instanceId (enum[string], required) - a platform-specific unique identifier
    + Members
        + InstanceID - utilize when platform is android
        + identifierForVendor - utilize when platform is ios